### PR TITLE
Replace calls to GetShallowClone

### LINKED ISSUE #119: File_Toolkit: Replace calls to Clone methods with calls to Base DeepClone or ShallowClone
#### Broken rules:
See https://github.com/BHoM/admin/issues/9

#### Suggestions to restore compliance:
https://github.com/BHoM/admin/issues/9#issuecomment-709032648

### PR DESCRIPTION
**Pull request by alelom**
### Issues addressed by this PR

Closes #119

### Test files

No functional change.

### CODE REVIEW

File: File_Adapter/AdapterActions/Push.cs [hunk 1]
```diff
@@ -94,7 +94,7 @@ public override List<object> Push(IEnumerable<object> objects, string tag = "",
 
             List<IResource> createdFiles = new List<IResource>();
 
-            List<IResource> filesOrDirs = objects.OfType<IResource>().Select(fd => fd.GetShallowClone() as IResource).ToList();
+            List<IResource> filesOrDirs = objects.OfType<IResource>().Select(fd => fd.ShallowClone() as IResource).ToList();
```
Comment (FraserGreenroyd) [inline File_Adapter/AdapterActions/Push.cs:97]:
```suggestion
            List<IResource> filesOrDirs = objects.OfType<IResource>().Select(fd => fd.ShallowClone()).ToList();
```

**Review by FraserGreenroyd — CHANGES_REQUESTED** [review]

**Comment by FraserGreenroyd** [comment]
@BHoMBot check required
@BHoMBot check dataset-compliance
@BHoMBot check copyright-compliance
@BHoMBot check ready-to-merge

**Review by FraserGreenroyd — APPROVED** [review]
Code reviewed only.
